spring.application.name=tunhire
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/tunhire}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres123}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=${JWT_SECRET:H2buFRxPuMGtCJLFhzqQPCMsUyStmTE+ycIdqwoI6Gk=}
jwt.expiration-ms=${JWT_EXPIRATION:86400000}

