spring.application.name=tunhire
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/tunhire}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:tunhire}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:tunhire}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.open-in-view=false
